with open('dvc.yaml', 'w') as f:
    f.write('stages:\n')
    f.write('\n')
    f.write('  ingest:\n')
    f.write('    cmd: python src/ingest_data.py\n')
    f.write('    deps:\n')
    f.write('      - src/ingest_data.py\n')
    f.write('      - data/raw_pdfs\n')
    f.write('    params:\n')
    f.write('      - ingest.data_dir\n')
    f.write('      - ingest.output_path\n')
    f.write('    outs:\n')
    f.write('      - data/processed_data/raw_documents.pkl\n')
    f.write('\n')
    f.write('  chunk:\n')
    f.write('    cmd: python src/evaluate_chunking.py\n')
    f.write('    deps:\n')
    f.write('      - src/evaluate_chunking.py\n')
    f.write('      - data/processed_data/raw_documents.pkl\n')
    f.write('    params:\n')
    f.write('      - chunk.chunk_size\n')
    f.write('      - chunk.chunk_overlap\n')
    f.write('      - chunk.output_path\n')
    f.write('    outs:\n')
    f.write('      - data/processed_data/document_chunks.pkl\n')
    f.write('    metrics:\n')
    f.write('      - data/processed_data/chunk_metrics.json:\n')
    f.write('          cache: false\n')
    f.write('\n')
    f.write('  embed:\n')
    f.write('    cmd: python src/create_embeddings.py\n')
    f.write('    deps:\n')
    f.write('      - src/create_embeddings.py\n')
    f.write('      - data/processed_data/document_chunks.pkl\n')
    f.write('    params:\n')
    f.write('      - embed.model_name\n')
    f.write('      - embed.collection_name\n')
    f.write('      - embed.qdrant_url\n')
    f.write('\n')

print('dvc.yaml written')
import os
print(f'Size: {os.path.getsize("dvc.yaml")} bytes')